server:
  applicationConnectors:
  - type: http
    port: 8989
    # for security reasons bind to localhost
    bindHost: localhost

osmFile: /path/to/osm-file.osm.pbf
tmpFiles: /path/to/tmp/folder
geoJsonFile: /path/to/geoJson/file.json